[package]
name = "szfs"
version = "0.1.0"
edition = "2021"

[features]
debug = []

[[bin]]
name = "fs-walker"
src = "src/fs-walker.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
